services:
  postgres:
    image: postgres:16-alpine
    container_name: ordermanager-postgres
    environment:
      POSTGRES_DB: OrderManagerDb
      POSTGRES_USER: ordermanager
      POSTGRES_PASSWORD: OrderManager123!
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ordermanager-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ordermanager.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: